### PR TITLE
feat: add a stripe logo as an svg to the backend

### PR DESCRIPTION
**Pull request by RobinTheHood**

### CODE REVIEW

**Comment by grandeljay** [comment]
Is this the intended look?

image

**Comment by grandeljay** [comment]
The current version of modified doesn't seem to show payment icons any more
image

**Comment by RobinTheHood** [comment]
Since we still support modified 2.0.6.0, I changed it so that an icon is only displayed in modified 2.0.6.0.

**Review by grandeljay — APPROVED** [review]
LGTM

**Pull request merged**
